### ISSUE TITLE
proposition de bots quizz

### ISSUE THREAD

**Issue by kerthe17** [Vanerac/drake-issues#14]
j'aimerai proposé un bots quizz en français différent du seul bot quizz francais qui existe.

il proposerai des questions avec plusieurs réponse proposé (donc une bonne réponse), si la personne répond juste il gagne 1 point, si elle se trompe elle perd 1 point.

système de base pour pouvoir le lancer ou le stopper avec une commande simple, un classement et pouvoir le reset.

par contre pouvoir choisir entre plusieurs temps pour répondre (exemple 15sec, 30sec ou autre pour répondre a la question) et le temps entre chaque question (temps entre la fin de la question et le début de la suivante)

quelque idée en plus que je vais mettre dans dautre poste a la suite ^^

**Comment by Vanerac** [comment]
@kerthe17 tu peut continuer ton poost en commentaire

**Comment by kerthe17** [comment]
première idée 

mettre un système de catégorie de question

exemple : musique, jeux vidéo, fortnite, cinéma, culture général, ect.....

**Comment by kerthe17** [comment]
deuxième idée 

pouvoir rajouter des questions sans obligatoirement passer par le créateur du bot si c'est possible

**Comment by Vanerac** [comment]
@kerthe17  au debut je peut faire une petite liste pour les questions de bases.
Pour ce qui concerne les questions custom , elles seraient limites  a 4 ou 5 par serveur

**Comment by kerthe17** [comment]
sa fait pas beaucoup sa xD

**Comment by Vanerac** [comment]
tu placerais la limite a combien toi? je peut le monter a dix stv

**Comment by kerthe17** [comment]
heu bah sa dépendrais du système pour les mettre

si sa doit être validé par le créateur ou si sa sera un système de vote par les gens et quand sa dépasse un seuil sa se valide ^^

**Comment by Vanerac** [comment]
Enfaite je voyais plus ca comme un parametre, tu l'ajoute pour ton serv et elles sont disponibles dans une categorie a part

**Comment by Vanerac** [comment]
et une limite le nombre de question personalises a 10 par serv

**Comment by kerthe17** [comment]
bah si les questions sont juste pour le serveur pourquoi limité ? 

et les questions de cet catérogie peuvent etre vu par le créateur du bot?

**Comment by Vanerac** [comment]
Je limit pour eviter les abus, mais je vais voir comment  je stocke les questions et les reponses
Et puisque j'ai access a la DB je peut voir les questions et les reponses

**Comment by kerthe17** [comment]
bah si tu donne les droits de mettre des questions que au gens qui sont modo, admin ou chef sa passerai non?

**Comment by Vanerac** [comment]
Oui c'est ce qui est prevu, les admin peuvent ajouter des questions

**Comment by kerthe17** [comment]
bah voila je pense pas que y aura vraiment d'abus comme sa ^^
et si toi tu y a accès en plus tu pourra rajouter les questions intéressant en plus dans les bonnes catégorie

**Comment by Vanerac** [comment]
le but c'est que j'ai pas a gerer ce genre de choses
je vais juste mettre un limite a 10 ou 15 ou eviter que la DB sois trop dense
et je vais faire en sorte de faire une grosse reserve de question de bases
D'ailleurs si tu as des propositions je suis prenneur
