### ISSUE TITLE
tempban

### ISSUE THREAD

**Issue by pakinus** [Vanerac/drake-issues#29]
quand la personne est déban envoie auto d'invite du serv en mp

**Comment by Vanerac** [comment]
Le bot peut pas lui envoyer de mp si il est ban du serv

**Comment by pakinus** [comment]
ah merde c dommage

**Comment by pakinus** [comment]
au pire il envoie avant de le ban 🤔

**Comment by Vanerac** [comment]
Pourquoi tu as re ouvert

**Comment by pakinus** [comment]
parce que sinnon tu vois pas mon message que j'ai mit ?

**Comment by Vanerac** [comment]
Si g la notif
