### ISSUE TITLE
giveaway

### ISSUE THREAD

**Issue by pakinus** [Vanerac/drake-issues#33]
fonction comme le giveaway bot

**Comment by Vanerac** [comment]
🤔

**Comment by Vanerac** [comment]
avec des reaction?

**Comment by pakinus** [comment]
ouais comme le giveaway bot genre tout le monde appuie et sa pioche un au hasard

**Comment by pakinus** [comment]
rajouter un reroll

**Comment by Vanerac** [comment]
reroll immediat? ou qui relance avec le timer?

**Comment by pakinus** [comment]
immédiat si ils ont pas eu le temps de participer sa c leur problèmes
